config/routes.rb
Rails.application.routes.draw do
  resources :users, :badge_set_entries, :badge_sets, :comp_tiers, :badge_nominations, :nomination_votes
  resources :badges do
    member { get :propose, :accept, :reject, :request_removal }
    collection { get :detailed }
  end

  # for attention points app
  resources :assignments
  resources :roles do
    member { get :assign }
  end

  get ':controller/:action/:category'
  root to: 'badges#index'
  get 'about' => 'visitors#about'
  get 'help' => 'visitors#help'
  get 'validations' => 'nomination_votes#index'
  get 'nominations' => 'badge_nominations#index'
  get 'holders' => 'users#holders'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :badge_nominations
  has_many :holders, through: :badge_nominations, source: :user
  belongs_to :proposer, class_name: 'User'

  has_many :badge_set_entries
  has_many :badge_sets, through: :badge_set_entries
  has_many :objections, class_name: 'BadgeObjection'

  scope :accepted, -> { where(status: 'accepted') }
  scope :proposed, -> { where(status: 'proposed') }
  scope :draft, -> { where(status: 'draft') }
  
  validates :name, presence: true
  validates :description, presence: true

  def relevant_date
    if status == 'accepted'
      acceptance_date || created_at.to_date
    elsif status == 'proposed'
      proposal_date || created_at.to_date
    else
      created_at.to_date
    end
  end

  def self.filter_by(group, status)
    return Badge.all if group == nil && status == nil
    has_group = Badge.where(group: group)
    has_status = Badge.where(status: status)

    return has_status if has_group == []
    return has_group if has_status == []
    has_group & has_status
  end

  def self.groups
    Badge.pluck(:group).compact.uniq
  end

  def active_or_not
    if active?
      removal_requested? ? "active, removal requested #{removal_requested.strftime('%b-%d')}" : 'active'
    else
      'inactive'
    end
  end

  def status_with_date
    return nil if status == nil
    if status == 'accepted'
      acceptance_date ? status.capitalize + ' on ' + acceptance_date.strftime('%b-%-d') : status.capitalize
    elsif status == 'proposed'
      proposal_date ? status.capitalize + ' on ' + proposal_date.strftime('%b-%-d') : status.capitalize
    else
      status.capitalize
    end    
  end

  # TODO: make sure voted badges still included
  def current_holders
    badge_nominations.select{ |bn| bn.accepted? }.map{ |bn| bn.user }
  end

  def current_holder_emails
    current_holders.map(&:mailto).join(', ')
  end

  def current_holder_names
    holders = badge_nominations.select{ |bn| bn.accepted? }.map{ |bn| bn.user.short + ' ' + bn.current_level.to_s }
    holders.count > 0 ? holders.join(', ') : 'There are no current badge holders'
  end
  
  def accepted?
    status == 'accepted'
  end

  def detailed_levels
    (1..9).map{ |i| [i.to_s + ': ' + send('level_' + i.to_s), i] unless send('level_' + i.to_s) == '' }.compact
  end

  def has_focus?
    focus && focus != ''
  end

  def has_levels?
    detailed_levels != []
  end
  
  def name_with_focus
    if name
      has_focus? ? name + ' (' + focus + ')' : name
    else
      has_focus? ? 'unnamed' + ' (' + focus + ')' : name
    end
  end

  def safe_name_with_focus
    name ? name_with_focus : '(Badge Missing)'
  end

  def enough_holders
    holders.count >= 5
  end

  def reset_levels
    update_attributes(
      level_1: '',
      level_2: '',
      level_3: '',
      level_4: '',
      level_5: '',
      level_6: '',
      level_7: '',
      level_8: '',
      level_9: ''
    )
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy, :propose, :accept, :reject, :request_removal]
  before_action :authenticate_user!, except: [:index, :detailed, :show]
  before_action :check_auth, only: [:edit, :accept, :reject]
  before_action :warn_if_not_proposer, only: [:edit]

  def index
    @badges = Badge.order(:status).order(:name)
    @accepted = Badge.accepted.order(:status).order(:name)
    @proposed = Badge.proposed.order(:status).order(:name)
    @draft = Badge.draft.order(:status).order(:name)
  end

  def detailed
    index
  end

  def show
  end

  def new
    @users = librarian_or_admin? ? User.all : [current_user]
    template = Badge.find_by_id(params[:template_id])
    @badge = template ? template.dup : Badge.new
    @badge.focus = ''
    @badge.status = template ? 'proposed' : 'draft'
  end

  def edit
    @users = librarian_or_admin? ? User.all : [current_user]
  end

  def create
    @badge = Badge.new(badge_params)
    @badge.status = 'draft'
    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        @users = librarian_or_admin? ? User.all : [current_user]
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  def request_removal
    @badge.removal_requested = Time.now
    if @badge.save
      redirect_to :back, notice: 'Badge removal request processed.  Please notify Badge Librarian via Slack or e-mail.'
    else
      redirect_to :back, alert: 'Badge removal request could not be processed.'
    end
  end

  def propose
    @badge.status = 'proposed'
    @badge.proposal_date = DateTime.now.to_date
    if @badge.save
      redirect_to @badge, notice: 'Badge proposed.  Please notify Badge Librarian via Slack or e-mail.'
    else
      redirect_to @badge, alert: 'Unable to change badge status to "proposed".'
    end
  end

  def reject
    o = @badge.objections.build(librarian: current_user, objection: true)
    if o.save && @badge.update_attributes(status: 'draft')
      redirect_to @badge, notice: 'Badge status successfully changed back to "draft"'
    else
      redirect_to @badge, alert: 'Unable to change badge status back to "draft".'
    end
  end

  def accept
    o = @badge.objections.build(librarian_id: params[:librarian_id], objection: false)
    notice_or_alert = nil
    if o.valid?      
      if last_non_objection?
        o.save!
        @badge.update_attributes(status: 'accepted', acceptance_date: DateTime.now.to_date)
        notice_or_alert = { notice: "Your (last remaining) non-objection was recorded. Badge status is now 'accepted'" }
      else
        o.save!
        notice_or_alert = { notice: "Your non-objection was recorded. Badge status unchanged" }
      end
    else
      notice_or_alert = { alert: "Your non-objection was invalid." }
    end
    redirect_to @badge, notice_or_alert
  end

  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @badge.badge_sets.count > 0
      notice_or_alert = { alert: 'This badge is part of at least one badge set.  Delete those first and try again.' }
      redirect_path = :back
    elsif @badge.badge_nominations.count > 0
      notice_or_alert = { alert: 'There are pending nominations for this badge.  Delete those first and try again.' }
      redirect_path = :back
    else
      notice_or_alert = { notice: 'Badge was successfully destroyed.'}
      redirect_path = URI(request.referer).path == '/badges' ? :back : holders_path
      @badge.destroy
    end
    respond_to do |format|
      format.html { redirect_to redirect_path, notice_or_alert }
      format.json { head :no_content }
    end
  end

  private
    def set_badge
      @badge = Badge.find(params[:id])
    end

    def badge_params
      params.require(:badge).permit(:name, :description, :proposer_id, :status, :proposal_date, :levels, :level_1,
        :level_2, :level_3, :level_4, :level_5, :level_6, :level_7, :level_8, :level_9, :focus, :feedback,
        :mechanism, :acceptance_date, :url, :comments, :active, :removal_requested, :group)
    end

    def check_auth
      return if librarian_or_admin?
      return if @badge.status == 'draft'
      where = request.env["HTTP_REFERER"] || root_path
      redirect_to where, alert: 'Only librarians and admins can take that action.'
    end

    def warn_if_not_proposer
      if @badge.proposer && @badge.proposer != current_user
        flash.now[:alert] = "This badge was proposed by #{@badge.proposer.short}.  Do you have the proposer's permission to edit it?"
      end
    end

    def last_non_objection?
      @badge.objections.count == User.librarians.count - 1
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_actions.html.haml
- if badge.status == 'draft'
  %span.green= link_to 'Edit', edit_badge_path(badge)
- elsif librarian_or_admin?
  %span.green.admin-only= link_to 'Edit', edit_badge_path(badge)

- if librarian_or_admin?
  \|
  %span.green.admin-only= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure you want to permanently delete this badge?' }
  - if badge.status == 'proposed'
    \|
    %span.green.admin-only= link_to 'Object or not...', badge
- if badge.status == 'draft'
  \|
  %span.green= link_to 'Propose', propose_badge_path(badge)
- if badge.status == 'accepted'
  \|
  %span.green= link_to 'Remove', request_removal_badge_path(badge), title: 'Request removal, actually.  This takes effect when all Badge Librarians non-object, or if they take no action within 7 days'
- if badge.has_focus?
  \|
  %span.green= link_to 'Duplicate', new_badge_path(template_id: badge.id), title: 'Open up new badge form, with new focus but all other fields exactly the same.'

app/views/badges/_badge.html.haml
%tr
  - nomination_link = link_to 'Nominate For...', new_badge_nomination_path(badge_id: badge.id)
  %td.green= badge.status == 'accepted' ? nomination_link : '' if user_signed_in?
  %td= link_to badge.name_with_focus, badge
  %td= badge.status.capitalize
  %td
    = image_tag badge.proposer.gravatar(20) rescue nil
    = badge.proposer.try(:short)
  %td= badge.relevant_date
  - if librarian_or_admin?
    %td
      %span.admin-only= badge.group
  / %td= badge.active_or_not
  %td= render 'badges/actions', badge: badge

app/views/badges/_card.html.haml
%h5= link_to badge.name_with_focus, badge
%ul
  %li= badge.description
  %li
    - if badge.accepted? && user_signed_in? && badge.holders.include?(current_user)
      %strong= "You hold this badge at level #{current_user.badge_level(badge)}"

app/views/badges/_detailed_badge.html.haml
%ul.no-bullet.inline-list.toobig
  %li.badge19-initial.box= render 'card', badge: badge
  - unless badge.level_1 == ''
    %li.badge19= "Level 1: #{badge.level_1}"
  - unless badge.level_2 == ''
    %li.badge19= "Level 2: #{badge.level_2}"
  - unless badge.level_3 == ''
    %li.badge19= "Level 3: #{badge.level_3}"
  - unless badge.level_4 == ''
    %li.badge19= "Level 4: #{badge.level_4}"
  - unless badge.level_5 == ''
    %li.badge19= "Level 5: #{badge.level_5}"
  - unless badge.level_6 == ''
    %li.badge19= "Level 6: #{badge.level_6}"
  - unless badge.level_7 == ''
    %li.badge19= "Level 7: #{badge.level_7}"
  - unless badge.level_8 == ''
    %li.badge19= "Level 8: #{badge.level_8}"
  - unless badge.level_9 == ''
    %li.badge19= "Level 9: #{badge.level_9}"
%hr

app/views/badges/_dropdown_item.html.haml
%li.dropdown_badge= link_to badge.name_with_focus, new_badge_nomination_path(badge_id: badge.id)

app/views/badges/_form.html.haml
= simple_form_for(@badge) do |f|
  = f.error_notification

  - name_placeholder = 'See badge library for examples (e.g. Energy Management)'
  - focus_placeholder = 'If applicable e.g. Making: Tools/Legal Writing'
  - description_placeholder = 'Summary of Badge. (e.g. Energy Management: Ability to move rhythmically between spending and renewing energy to fuel sustainable engagement and high performance.)'
  - mechanism_placeholder = 'If mechanism for gaining/losing a badge exists, add here. (e.g. Level 6 or higher: Take and submit Energy Audit https://drive.google.com/open?id=0BxNFxfz-fjYhQXpVUjB3dTVheHc)'
  .form-inputs
    - values = [['Draft', 'draft'], ['Proposed', 'proposed'], ['Accepted', 'accepted']]
    .large-3.small-3.columns
      - if librarian_or_admin? || @badge.persisted?
        = f.association :proposer, collection: @users, label_method: :short, include_blank: true
      - else
        = f.association :proposer, collection: @users, label_method: :short, selected: current_user.try(:id)
    - if librarian_or_admin?
      .large-3.small-3.columns.admin-only= f.input :status, collection: values, include_blank: true
      .large-3.small-3.columns.admin-only= f.input :proposal_date, include_blank: true
      .large-3.small-3.columns.admin-only= f.input :acceptance_date, include_blank: true

    %hr
    - if librarian_or_admin?
      .large-3.small-12.columns= f.input :name, label: 'Badge Name', autofocus: !params[:template_id], placeholder: name_placeholder
      .large-3.small-12.columns= f.input :focus, placeholder: focus_placeholder, autofocus: !!params[:template_id]
      .large-3.small-12.columns.admin-only= f.input :group
      .large-3.small-12.columns= f.input :url, label: 'Supporting URL'
    - else
      .large-4.small-12.columns= f.input :name, label: 'Badge Name', autofocus: !params[:template_id], placeholder: name_placeholder
      .large-4.small-12.columns= f.input :focus, placeholder: focus_placeholder, autofocus: !!params[:template_id]
      .large-4.small-12.columns= f.input :url, label: 'Supporting URL'
    %div
    .large-4.small-12.columns= f.input :description, label: 'Basic Badge Description', input_html: {rows: 5}, placeholder: description_placeholder
    .large-4.small-12.columns= f.input :mechanism, label: 'Optional Mechanism for gaining/losing', input_html: {rows: 5}, placeholder: mechanism_placeholder
    .large-4.small-12.columns= f.input :comments, label: 'Supporting Comments', input_html: {rows: 5}
    %div

    %hr
    %h4 Badge Level Descriptions
    .large-12.columns
      %p
        If this badge includes levels, write each level’s progression.
        %br
        Complete the sentence “I have repeatedly demonstrated that..."
        %br
        Not all badges need levels, nor do all levels (1 to 9) need to be included.

    - level_1_placeholder = ''
    - level_2_placeholder = ''
    - level_3_placeholder = ''
    - level_4_placeholder = ''
    - level_5_placeholder = ''
    - level_6_placeholder = ''
    - level_7_placeholder = ''
    - level_8_placeholder = ''
    - level_9_placeholder = ''
    .large-4.small-12.columns= f.input :level_1, label: 'Level 1 Description', input_html: {rows: 4}, placeholder: level_1_placeholder
    .large-4.small-12.columns= f.input :level_2, label: 'Level 2 Description', input_html: {rows: 4}, placeholder: level_2_placeholder
    .large-4.small-12.columns= f.input :level_3, label: 'Level 3 Description', input_html: {rows: 4}, placeholder: level_3_placeholder
    %div
    .large-4.small-12.columns= f.input :level_4, label: 'Level 4 Description', input_html: {rows: 4}, placeholder: level_4_placeholder
    .large-4.small-12.columns= f.input :level_5, label: 'Level 5 Description', input_html: {rows: 4}, placeholder: level_5_placeholder
    .large-4.small-12.columns= f.input :level_6, label: 'Level 6 Description', input_html: {rows: 4}, placeholder: level_6_placeholder
    %div
    .large-4.small-12.columns= f.input :level_7, label: 'Level 7 Description', input_html: {rows: 4}, placeholder: level_7_placeholder
    .large-4.small-12.columns= f.input :level_8, label: 'Level 8 Description', input_html: {rows: 4}, placeholder: level_8_placeholder
    .large-4.small-12.columns= f.input :level_9, label: 'Level 9 Description', input_html: {rows: 4}, placeholder: level_9_placeholder

  %hr

  .form-actions
    - if params[:action] == 'new'
      = f.button :submit, 'Create Badge Draft'
    - else
      = f.button :submit, 'Save'

app/views/badges/_objections.html.haml
%span.green.admin-only= link_to 'Object', reject_badge_path(@badge)
- User.librarians.each do |lib|
  \|
  %span.admin-only= link_to "Non-Object as #{lib.short}", accept_badge_path(librarian_id: lib.id)
%br
= render @badge.objections

app/views/badges/detailed.html.haml
%h3
  HolacracyOne Badge Library

%h5
  = link_to('All', detailed_badges_path) + ' | '
  = link_to('Accepted', detailed_badges_path(status: 'accepted')) + ' | '
  = link_to('Proposed', detailed_badges_path(status: 'proposed')) + ' | '
  = link_to('Draft', detailed_badges_path(status: 'draft'))
  %button= link_to 'Propose New Badge', new_badge_path

- if params[:status].nil? || params[:status] == 'accepted'
  %p
    %hr
    .row
    %h3 Accepted Badges
    - @accepted.each do |badge|
      = render 'detailed_badge', badge: badge

- if params[:status].nil? || params[:status] == 'proposed'
  %p
    %hr
    .row
    %h3 Proposed Badges
    - @proposed.each do |badge|
      = render 'detailed_badge', badge: badge

- if params[:status].nil? || params[:status] == 'draft'
  %p
    %hr
    .row
    %h3 Draft Badges
    - @draft.each do |badge|
      = render 'detailed_badge', badge: badge

app/views/badges/index.html.haml
%h3
  - if params[:status] == 'accepted'
    HolacracyOne Badge Library
  - else
    HolacracyOne Badges

%h5
  - if params[:group]
    .badge-group= link_to 'All', badges_path(group: nil, status: params[:status])
    - Badge.groups.each do |g|
      .badge-group= link_to g.capitalize, badges_path(status: params[:status], group: g)

%h5
  = link_to('All', badges_path(group: params[:group]))
  - if !params[:status]
    %span.bubble= @badges.count
  - else
    = link_to @badges.count, badges_path(status: nil, group: params[:group])
  \|
  - if params[:status] == 'accepted'
    %span.bubble= @accepted.count
  - else
    = link_to @accepted.count, badges_path(status: 'accepted', group: params[:group])
  = link_to('Accepted', badges_path(status: 'accepted', group: params[:group])) + ' | '
  - if params[:status] == 'proposed'
    %span.bubble= @proposed.count
  - else
    = link_to @proposed.count, badges_path(status: 'proposed', group: params[:group])
  = link_to('Proposed', badges_path(status: 'proposed', group: params[:group])) + ' | '
  - if params[:status] == 'draft'
    %span.bubble= link_to @draft.count, badges_path(status: 'draft', group: params[:group])
  - else
    = link_to @draft.count, badges_path(status: 'draft', group: params[:group])
  = link_to('Draft', badges_path(status: 'draft', group: params[:group]))

%table#badges-table.compact
  %thead
    %tr
      %th.nosort
      %th Badge Name
      %th Status
      %th Proposer
      %th Date
      / %th
      - if librarian_or_admin?
        %th 
          %span.admin-only Group
      %th.nosort
  %tbody
    = render @badges if !params[:status]
    = render @accepted if params[:status] == 'accepted'
    = render @proposed if params[:status] == 'proposed'
    = render @draft if params[:status] == 'draft'

%button= link_to 'Detailed View', detailed_badges_path
/ - if params[:group]
/   %button= link_to 'Hide Groups', badges_path(status: params[:status])
/ - else
/   %button= link_to 'Show Groups', badges_path(group: 'none', status: params[:status])
- if librarian_or_admin?
  %button= link_to 'Add New Badge', new_badge_path
- else
  %button= link_to 'Propose New Badge', new_badge_path

app/views/badges/new.html.haml
%h1
  Add New Badge
  = "(Duplicated with New Focus)" if params[:template_id]

.space-20
= render 'form'

app/views/badges/show.html.haml
%p.large-12.medium-12
  %h2= "#{@badge.name_with_focus} Badge"
  .row
    %strong.large-2.columns.text-right Status
    .large-10.columns= "#{@badge.status.capitalize} as of #{@badge.relevant_date.strftime('%b-%d')}"
    .large-4.columns
  .row
    %strong.large-2.medium-2.small-2.columns.text-right Proposer
    .large-6.medium-6.small-6.columns= @badge.proposer.try(:name)
    .large-4.medium-4.small-4.columns
  - if user_signed_in?
    .row
      %strong.large-2.columns.text-right
        = @badge.current_holders.count
        Current Holders
      .large-6.columns= @badge.current_holder_names
      .large-4.columns
  .row
    %strong.large-2.columns.text-right Description
    .large-6.columns.box= @badge.description
    .large-4.columns
  - if @badge.mechanism && @badge.mechanism != ''
    .row
      %strong.large-2.columns.text-right Mechanism
      .large-6.columns.box= @badge.mechanism
      .large-4.columns
  - if @badge.comments && @badge.comments != ''
    .row
      %strong.large-2.columns.text-right Comments
      .large-6.columns.box= @badge.comments
      .large-4.columns
  - if @badge.url
    .row
      %strong.large-2.columns.text-right Supporting URL
      .large-6.columns= link_to @badge.url, @badge.url
      .large-4.columns
  .space-20
  .row
    %strong.large-2.columns.text-right Objections
    .large-6.columns= render 'objections'
    .large-4.columns

%br
%hr
.medium-4.large-4.columns
  .badge33
    %b Level 1:
    = @badge.level_1
.medium-4.large-4.columns
  .badge33
    %b Level 2:
    = @badge.level_2
.medium-4.large-4.columns
  .badge33
    %b Level 3:
    = @badge.level_3
%br
%hr
.medium-4.large-4.columns
  .badge33
    %b Level 4:
    = @badge.level_4
.medium-4.large-4.columns
  .badge33
    %b Level 5:
    = @badge.level_5
.medium-4.large-4.columns
  .badge33
    %b Level 6:
    = @badge.level_6
%br
%hr
.medium-4.large-4.columns
  .badge33
    %b Level 7:
    = @badge.level_7
.medium-4.large-4.columns
  .badge33
    %b Level 8:
    = @badge.level_8
.medium-4.large-4.columns
  .badge33
    %b Level 9:
    = @badge.level_9
%br
%hr

%button= link_to 'All Badges', badges_path
= render 'actions', badge: @badge