config/routes.rb
Rails.application.routes.draw do
  resources :users, :badge_set_entries, :badge_sets, :comp_tiers, :badge_nominations, :nomination_votes
  resources :badges do
    member { get :propose, :accept, :reject, :request_removal }
    collection { get :detailed }
  end

  # for attention points app
  resources :assignments
  resources :roles do
    member { get :assign }
  end

  get ':controller/:action/:category'
  root to: 'badges#index'
  get 'about' => 'visitors#about'
  get 'help' => 'visitors#help'
  get 'validations' => 'nomination_votes#index'
  get 'nominations' => 'badge_nominations#index'
  get 'holders' => 'users#holders'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/badge_set.rb
class BadgeSet < ActiveRecord::Base
  belongs_to :proposer, class_name: 'User'
  belongs_to :comp_tier
  has_many :badge_set_entries
  has_many :badges, through: :badge_set_entries
  has_many :users
  
  def name_and_comp_tier
    name + ' (' + comp_tier.name_and_monthly_draw + ')'
  end
end

app/controllers/badge_sets_controller.rb
class BadgeSetsController < ApplicationController
  before_action :set_badge_set, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @badge_sets = BadgeSet.all
  end

  def show
  end

  def new
    @badge_set = BadgeSet.new
  end

  def edit
  end

  def create
    @badge_set = BadgeSet.new(badge_set_params)

    respond_to do |format|
      if @badge_set.save
        format.html { redirect_to new_badge_set_entry_path(badge_set_id: @badge_set.id), notice: 'Badge set was successfully created.' }
        format.json { render :show, status: :created, location: @badge_set }
      else
        format.html { render :new }
        format.json { render json: @badge_set.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @badge_set.update(badge_set_params)
        format.html { redirect_to @badge_set, notice: 'Badge set was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge_set }
      else
        format.html { render :edit }
        format.json { render json: @badge_set.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @badge_set.destroy
    respond_to do |format|
      format.html { redirect_to badge_sets_url, notice: 'Badge set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_badge_set
      @badge_set = BadgeSet.find(params[:id])
    end

    def badge_set_params
      params.require(:badge_set).permit(:proposer_id, :name, :comp_tier_id)
    end
end

app/helpers/badge_sets_helper.rb
module BadgeSetsHelper
end

app/views/badge_sets/_badge_set.html.haml
.large-4.medium-6.small-12.columns
  .badge-set
    .valuation= link_to "#{badge_set.comp_tier.try(:name_and_monthly_draw)}/month", comp_tiers_path
    %h5= link_to badge_set.name, badge_set
    - badge_set.badge_set_entries.sort_by(&:badge_set_id_and_badge_name).each do |e|
      = link_to e.badge.try(:name_with_focus), e.badge || '(Missing Badge)'
      = e.level
      %br
  %br
  %span.green= link_to 'All Badge Sets —', badge_sets_path unless params[:action] == 'index'
  - if librarian_or_admin?
    %span.admin-only= link_to 'Edit', edit_badge_set_path(badge_set)
    \|
    %span.admin-only= link_to 'Destroy Badge Set', badge_set, :method => :delete, :data => { :confirm => 'Are you sure?' }
  .space-30

app/views/badge_sets/_form.html.haml
= simple_form_for(@badge_set) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, label: 'Name (optional)'
    = f.association :proposer, label_method: :short
    = f.association :comp_tier, label_method: :name_and_monthly_draw

  .form-actions
    = f.button :submit

app/views/badge_sets/_inline.html.haml
- contents = badge_set.badge_set_entries.map{ |e| "#{e.badge.try(:name)} #{e.level}" }.join(' ')
= link_to badge_set.name ? badge_set.name : 'No name', badge_set, title: contents

app/views/badge_sets/edit.html.haml
%h1 Editing badge_set

= render 'form'

= link_to 'Show', @badge_set
\|
= link_to 'Back', badge_sets_path

app/views/badge_sets/index.html.haml
%h1 Badge Valuation Database

= render @badge_sets

%hr

- if librarian_or_admin?
  .admin-only
    %button= link_to 'New Badge Set', new_badge_set_path

app/views/badge_sets/new.html.haml
%h1 New Badge Set

= render 'form'

= link_to 'Back', badge_sets_path

app/views/badge_sets/show.html.haml
%h2= @badge_set.name

= render 'badge_set', badge_set: @badge_set