config/routes.rb
Rails.application.routes.draw do
  resources :users, :badge_set_entries, :badge_sets, :comp_tiers, :badge_nominations, :nomination_votes
  resources :badges do
    member { get :propose, :accept, :reject, :request_removal }
    collection { get :detailed }
  end

  # for attention points app
  resources :assignments
  resources :roles do
    member { get :assign }
  end

  get ':controller/:action/:category'
  root to: 'badges#index'
  get 'about' => 'visitors#about'
  get 'help' => 'visitors#help'
  get 'validations' => 'nomination_votes#index'
  get 'nominations' => 'badge_nominations#index'
  get 'holders' => 'users#holders'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :comp_admin, :admin, :librarian]

  has_many :badge_nominations
  has_many :badges, through: :badge_nominations
  belongs_to :badge_set

  after_initialize :set_default_role, :if => :new_record?

  default_scope { order(:short) }
  scope :bootstrapper, -> { where(bootstrapper: true) }
  scope :active, -> { where(active: true) }
  scope :librarians, -> { where(librarian: true) }

  has_many :roles, foreign_key: :filler_id

  def attention_points
    roles.map(&:controlled).sum
  end

  def percent_focus
    attention_points / 80.0
  end

  def self.role_fillers
    roles = Role.pluck(:filler_id).uniq.compact
    roles == [] ? nil : User.find(Role.pluck(:filler_id))
  end

  def self.random
    offset(rand(6)).first
  end

  def monthly_draw
    (badge_set ? badge_set.comp_tier.monthly_draw  : legacy_p_unit_grant) * focus_time / 100
  end

  def gravatar(size=24)
    gravatar_id = Digest::MD5.hexdigest(email.downcase) unless email.blank?
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=monsterid"    
  end

  def self.bootstrappers
    where(bootstrapper: true).map{ |b| b.short}.join(', ')
  end

  def badges_pending
    badge_nominations.pending.map{ |bn| bn.badge unless bn.accepted? }.compact
  end

  def badges_held
    badge_nominations.map{ |bn| bn.badge if bn.accepted? }.compact
  end

  def is_admin?
    role == 'admin'
  end

  def is_comp_admin?
    role == 'comp_admin'
  end

  def badge_level(badge)
    bn = BadgeNomination.find_by(user_id: self.id, badge_id: badge.id)
    bn.try(:current_level)
  end

  def grant_badge(badge, level)
    badge_nominations.create(badge: badge, status: 'accepted', level_granted: level)
  end

  def has_badge(badge)
    bn = BadgeNomination.find_by(user_id: self.id, badge_id: badge.id)
    bn.try(:accepted?)
  end

  def nomination(badge)
    BadgeNomination.find_by(user_id: self.id, badge_id: badge.id)
  end

  def set_default_role
    if User.count == 0
      self.role ||= :admin
    else
      self.role ||= :user
    end
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end
  
  def safe_name
    name ? name : '(User Name Missing)'
  end
  
  def safe_short_name
    short ? short : '(Short User Name Missing)'
  end

  def mailto
    name + ' <' + email + '>'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :holders]

  def index
    @users = User.order('short')
    @badges = Badge.accepted.order('name')
  end

  def holders
    @users = User.active.order('short')
    @badges = Badge.accepted.order('name')
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :badge_set_id, :glassfrog_id, :legacy_p_unit_grant,
        :librarian, :comp_admin, :bootstrapper, :focus_time, :active)
    end
end

app/views/users/_actions.html.haml
- if librarian_or_admin?
  &nbsp;
  %span.admin-only.green= link_to 'Edit', edit_user_path(user)

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    .large-4.medium-4.small-6.columns= f.input :name
    .large-4.medium-4.small-6.columns= f.input :short
    .large-4.medium-4.small-6.columns= f.input :glassfrog_id, label: 'GlassFrog person id'
    %div
    .large-4.medium-4.small-6.columns= f.association :badge_set, label_method: :name_and_comp_tier
    .large-4.medium-4.small-6.columns= f.input :legacy_p_unit_grant, label: 'Legacy P Unit Grant'
    .large-4.medium-4.small-6.columns= f.input :focus_time, label: '% Focus Time'
    = f.input :bootstrapper
    = f.input :comp_admin
    = f.input :librarian
    = f.input :active

  .form-actions
    = f.button :submit, 'Save User'

app/views/users/_user.html.haml
%tr
  %th.avatar= image_tag user.gravatar(30)
  %td= link_to user.name, "http://glassfrog.holacracy.org/people/#{user.glassfrog_id}"
  %td= user.badge_set ? link_to(user.badge_set.name, user.badge_set) : ''
  %td.text-center= link_to user.badges_held.count, holders_path
  %td.text-center= link_to user.badges_pending.count, holders_path
  %td.text-right= number_to_currency(user.legacy_p_unit_grant, precision: 0)
  %td.text-right= link_to number_to_currency(user.badge_set.comp_tier.monthly_draw, precision: 0), user.badge_set rescue ''
  %td.text-center= "#{user.focus_time}%"
  %td.text-right= number_to_currency(user.monthly_draw, precision: 0) rescue 0
  %td= render 'actions', user: user

app/views/users/edit.html.haml
%h1 Editing Badge

= render 'form'

= link_to 'Show', @badge
\|
= link_to 'Back', badges_path

app/views/users/holders.html.haml
%h3 HolacracyOne Badge Holders

%table#holders-grid
  %thead
    %tr
      %th
      - @users.each do |user|
        %th
          .text-center.min-width= link_to image_tag(user.gravatar(36)), user
          .text-center.min-width= link_to user.try(:short), user
  %tbody
    - @badges.each do |badge|
      %tr.stripe
        %th.badge-name= link_to badge.name_with_focus, badge, class: 'no-hover'
        - @users.each do |user|
          - text = user.badge_level(badge)
          - if text && text == 'NEV'
            %th.text-center= link_to image_tag('hourglass.png'), user.nomination(badge), class: 'no-hover'
          - elsif text && text == true
            %th.text-center= link_to image_tag('checkmark.png'), user.nomination(badge), class: 'no-hover'
          - elsif text
            %th.text-center= link_to text, user.nomination(badge)
          - else
            %th.text-center= link_to '+', new_badge_nomination_path(badge_id: badge.id, user_id: user.id), class: 'green-light'

.legend
  = image_tag('checkmark.png')
  \= No-levels badge granted
.legend
  = image_tag('hourglass.png')
  \= Not enough votes
.legend
  = image_tag('warning.png')
  \= Please bring to Compensation Administrator's attention

app/views/users/index.html.haml
%h3 HolacracyOne Users

.space-20
%table#users-table.compact
  %thead
    %tr
      %th.avatar.nosort &nbsp;
      %th User Name
      %th.nosort Badge Set
      %th.text-center Held
      %th.text-center Pending
      %th.text-right Grant Comp
      %th.text-right Badge Comp
      %th.text-center Focus
      %th.text-right Monthly Draw
      %th.nosort &nbsp;
  %tbody
    = render @users

app/views/users/show.html.haml
%h2= @user.name

%strong Email:
= @user.email
%br
%strong Role:
= @user.role
%br
%strong Special Access?
= librarian_or_admin?(@user)
%hr

%button= link_to 'All Users', users_path