config/routes.rb
Rails.application.routes.draw do
  resources :users, :badge_set_entries, :badge_sets, :comp_tiers, :badge_nominations, :nomination_votes
  resources :badges do
    member { get :propose, :accept, :reject, :request_removal }
    collection { get :detailed }
  end

  # for attention points app
  resources :assignments
  resources :roles do
    member { get :assign }
  end

  get ':controller/:action/:category'
  root to: 'badges#index'
  get 'about' => 'visitors#about'
  get 'help' => 'visitors#help'
  get 'validations' => 'nomination_votes#index'
  get 'nominations' => 'badge_nominations#index'
  get 'holders' => 'users#holders'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/badge_nomination.rb
class BadgeNomination < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
  has_many :validations, class_name: 'NominationVote', dependent: :delete_all
  has_many :validators, through: :validations, class_name: 'User'
  belongs_to :nominator, class_name: 'User'

  validates :user_id, presence: true
  validates :badge_id, presence: true
#  validates :status, presence: true

  validates_uniqueness_of :user_id, scope: :badge_id, message: "User has already been nominated for this badge."

  scope :pending, -> { where(status: 'pending').joins(:badge) }
  scope :accepted, -> { where(status: 'accepted') }

  def self.filter_by(status, user)
    if status == 'waiting'
      BadgeNomination.waiting_on(user)
    elsif status == 'mine'
      user.badge_nominations
    elsif status
      BadgeNomination.where(status: status)
    else
      BadgeNomination.all
    end
  end

  def validators
    validations.map{ |v| v.validator }.compact
  end

  def validated_by(who)
    validations.select { |v| v.validator_id == who.id }.count > 0
  end

  def self.not_validated_by(who)
    BadgeNomination.pending.reject{ |bn| bn.validated_by(who) }
  end

  def self.waiting_on(who)
    eligible = BadgeNomination.not_validated_by(who).reject{ |bn| bn.user == who }

    who.bootstrapper? ? eligible : eligible.select{ |bn| who.has_badge(bn.badge) }
  end

  def accepted?
    return true if status == 'accepted'
    if badge.has_levels?
      current_level && current_level.is_a?(Integer) && current_level > 0
    else
      current_level == true
    end
  end

  def nominated_badge_name
    badge.try(:name) || '(Since Deleted)'
  end

  def short_name_for_badge_level
    who = user.short || 'User Missing'
    what = badge.name || 'Badge Missing'
    base = who + " for "  + what
    badge.try(:has_levels?) ? base + ", Level " + level_nominated.to_s : base
  end

  def name_for_badge
    who = user.try(:name) || 'User Missing'
    what = badge.try(:name) || 'Badge Missing'
    who + " for "  + what
  end

  def grant
    update_attributes(status: 'accepted', effective_date: DateTime.now.to_date)
  end

  def current_level
    if status == 'expired'
      'EXP'
    elsif status == 'accepted'
      return true if !badge.try(:has_levels?)
      (level_granted.nil? || level_granted == '' || level_granted == 0) ? 'COMP' : level_granted
    elsif holder_votes.count > 1
      level_voted
    else
      level_bootstrapped
    end
  end

  def level_voted
    return 'NEV' unless holder_votes.count > 1
    badge.has_levels? ? holder_votes.map(&:level).sort.reverse[1] : true
  end

  def holder_votes
    return [] unless badge && badge.holders
    validations.select { |v| v.validator.has_badge(badge) }
  end

  def bootstrapper_majority
    (User.bootstrapper.count / 2.0).floor + 1
  end

  def level_bootstrapped
    return 'NEV' if bootstrapper_votes.count < bootstrapper_majority
    if badge.has_levels?
      bootstrapper_votes.sort{ |v| -v.level }[bootstrapper_majority - 1].level rescue nil
    else
      bootstrapper_votes.count >= bootstrapper_majority ? true : 'NEV'
    end
  end

  def bootstrapper_votes
    return [] unless validations && validations.count
    validations.select { |v| v.validator && v.validator.bootstrapper? }
  end

  def enough_badge_holders
    badge.enough_holders
  end
end

app/controllers/badge_nominations_controller.rb
class BadgeNominationsController < ApplicationController
  before_action :set_badge_nomination, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # before_action :check_auth, only: [:edit, :destroy]
  before_action :ensure_badge_id_param, only: [:new]

  def index
    status = params[:status]
    @badge_nominations = BadgeNomination.filter_by(status, current_user).sort_by(&:name_for_badge) rescue []
  end

  def show
    @validations = @badge_nomination.validations.order('level DESC')
  end

  def new
    @users = librarian_or_admin? ? User.all : [current_user]
    @nominator = current_user
    @badge_nomination = BadgeNomination.new
    @badge_nomination.status = 'pending'
    @badge_nomination.badge_id = params[:badge_id] if params[:badge_id]
    @badge = Badge.find_by_id(@badge_nomination.badge_id)
    @badge_nomination.user_id = params[:user_id] if params[:user_id]
    session[:badge_id] = @badge.id
  end

  def edit
    @nominator = current_user
    @badge = @badge_nomination.badge
    @users = librarian_or_admin? ? User.all : [current_user]
  end

  def create
    @badge_nomination = BadgeNomination.new(badge_nomination_params)
    if params[:badge_id]
      @badge_nomination.badge_id = params[:badge_id] 
      @badge = Badge.find_by_id(params[:badge_id])
    end

    respond_to do |format|
      if @badge_nomination.save
        safe_user = @badge_nomination.user.try(:name)
        safe_nom = @badge_nomination.badge.try(:name)
        format.html { redirect_to @badge_nomination, notice: "#{safe_user} successfully nominated for #{safe_nom}.  Consider requesting some validations." }
        format.json { render :show, status: :created, location: @badge_nomination }
      else
        params[:badge_id] = @badge_nomination.badge.id
        @users = librarian_or_admin? ? User.all : [current_user]
        format.html { render :new }
        format.json { render json: @badge_nomination.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @badge_nomination.update(badge_nomination_params)
        format.html { redirect_to @badge_nomination, notice: 'BadgeNomination was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge_nomination }
      else
        format.html { render :edit }
        format.json { render json: @badge_nomination.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @badge_nomination.destroy
    respond_to do |format|
      format.html { redirect_to holders_path, notice: 'BadgeNomination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_badge_nomination
      @badge_nomination = BadgeNomination.find(params[:id])
    end

    def badge_nomination_params
      params.require(:badge_nomination).permit(:name, :level_nominated, :level_granted, :status, :user_id, :nominator_id, :badge_id, :evidence, :effective_date)
    end

    def ensure_badge_id_param
      return if params[:badge_id]
      redirect_to root_path, alert: 'Please select "Nominate For..." in the navigation bar and select a specific Badge.'
    end
end

app/helpers/badge_nominations_helper.rb
module BadgeNominationsHelper
end

app/views/badge_nominations/_badge_nomination.html.haml
%tr
  %td.green= link_to 'Validate...', new_nomination_vote_path(badge_nomination_id: badge_nomination.id)
  %td= link_to badge_nomination.user.try(:name), badge_nomination.user ||= 'n/a'
  %td= badge_nomination.level_nominated ? "for level #{badge_nomination.level_nominated}" : 'for'
  %td= badge_nomination.badge ? link_to(badge_nomination.badge.name_with_focus, badge_nomination.badge) : '(Badge Missing)'
  %td= badge_nomination.status.capitalize ||= 'n/a'
  %td= badge_nomination.current_level ||= 'n/a'
  %td
    %span.green= link_to 'View', badge_nomination
    - if librarian_or_admin?
      %span.green.admin-only= link_to 'Edit', edit_badge_nomination_path(badge_nomination, badge_id: badge_nomination.badge.try(:id))
      %span.green.admin-only= link_to 'Destroy', badge_nomination, method: :delete, data: { confirm: 'Are you sure you want to permanently delete this nomination?' }
  %td
    - if librarian_or_admin? && badge_nomination.validators.count > 0
      by
      %span.admin-only= badge_nomination.validators.map(&:short).join(', ')
    - else
      = "#{badge_nomination.validators.count} times"

app/views/badge_nominations/_dropdown_item.html.haml
%li.dropdown_badge= link_to badge_nomination.short_name_for_badge_level, new_nomination_vote_path(badge_nomination_id: badge_nomination.id)

app/views/badge_nominations/_form.html.haml
= simple_form_for(@badge_nomination) do |f|
  = f.error_notification

  %div
  .form-inputs
    - if librarian_or_admin? || @badge_nomination.persisted?
      #user_id.large-3.small-3.columns
        = f.association :nominator, collection: @users, label_method: :short, include_blank: true
    - else
      #user_id.large-3.small-3.columns
        = f.association :nominator, collection: @users, label_method: :short, selected: @nominator.try(:id)
    .large-9.small.6.columns
      Description for
      %strong= link_to @badge.try(:name_with_focus), @badge
      %br
      = @badge.try(:description)
    %hr
    .large-3.small-3.columns
      #user_id= f.association :user, label: 'Nominee'
      - if params[:badge_id]
        = f.hidden_field :badge_id, value: params[:badge_id]
      - else
        #badge_id= f.association :badge, collection: Badge.accepted.order(:name), label_method: :name_with_focus
    .large-9.small-12.columns= f.input :evidence, label: 'Evidence and examples for this nomination', input_html: {rows: 5}
    %hr
    - if @badge.try(:has_levels?)
      Level: I have repeatedly demonstrated that…
      #level.box= f.input :level_nominated, collection: @badge.try(:detailed_levels), label: false, as: :radio_buttons, input_html: { class: 'radio-input' }
    - else
      #level= f.input :level_nominated, disabled: true, label: 'This badge has no levels.'
    %hr
    - if librarian_or_admin?
      %div.admin-only
        .large-3.small-6.columns.admin-only= f.input :status, collection: [['Pending', 'pending'], ['Accepted', 'accepted'], ['Expired', 'expired']]
        - if @badge.try(:has_levels?)
          .large-3.small-6.columns.admin-only= f.input :level_granted, collection: @badge.try(:detailed_levels)
        - else
          .large-3.small-6.columns.admin-only= f.input :level_granted, disabled: true, label: 'This badge has no levels.'
        .large-4.small-6.columns.admin-only= f.input :effective_date, include_blank: true
        .large-2.small-6.columns
    - else
      .large-3.small-3.columns= f.input :status, collection: [['Pending', 'pending']]      
    %hr

  .form-actions
    = f.button :submit, 'Nominate'

app/views/badge_nominations/create.html.haml
%h1 BadgeNominations#create
%p Find me in app/views/badge_nominations/create.html.haml

app/views/badge_nominations/edit.html.haml
%h1 Edit Badge Nomination

= render 'form'

app/views/badge_nominations/index.html.haml
%h3 Badge Nominations

%h5
  = link_to 'All', badge_nominations_path
  - if !params[:status]
    %span.bubble= @badge_nominations.count
  \|
  - if params[:status] == 'mine'
    %span.bubble= @badge_nominations.count
  = link_to 'Mine', badge_nominations_path(status: 'mine')
  \|
  - if params[:status] == 'pending'
    %span.bubble= @badge_nominations.count
  = link_to 'Pending', badge_nominations_path(status: 'pending')
  \|
  - if params[:status] == 'waiting'
    %span.bubble= @badge_nominations.count
  = link_to 'Waiting On My Validation', badge_nominations_path(status: 'waiting')
  \|
  - if params[:status] == 'accepted'
    %span.bubble= @badge_nominations.count
  = link_to 'Accepted', badge_nominations_path(status: 'accepted')

%table
  %tr
    %th
    %th Nominee
    %th
    %th Badge
    %th Status
    %th Level
    %th Actions
    %th Validated/Bootstrapped
  = render @badge_nominations

app/views/badge_nominations/new.html.haml
%h1= "Nominate for #{params[:badge_id] ? @badge.try(:name_with_focus) : ''} Badge"

.space-20
= render 'form'

app/views/badge_nominations/show.html.haml
- @bn = @badge_nomination
%p.large-12.medium-12
  %h3
    Nomination:
    = @badge_nomination.name_for_badge
  .row
    %strong.large-3.columns.text-right Nominated by
    .large-6.columns
      = @badge_nomination.nominator.try(:name)
      = "(at level #{@badge_nomination.level_nominated})"
    .large-3.columns
  .row
    %strong.large-3.columns.text-right Current Level
    .large-6.columns= @badge_nomination.current_level
    .large-3.columns

    .large-3.columns
  - if @badge_nomination.evidence && @badge_nomination.evidence != ''
    .row
      %strong.large-3.columns.text-right Evidence
      .large-6.columns.box= @badge_nomination.evidence
      .large-3.columns

%hr

- holders_count = @bn.badge.current_holders.count
- if holders_count > 1
  - body = "Your validation as badge holder is requested for #{badge_nomination_url(@bn)}\n\nEvidence submitted:\n\n #{@bn.evidence}"
  - subject = "[Badges App => Badge Holder] Please validate #{@bn.user.short} for #{@bn.badge.name} Badge at Level #{@bn.level_nominated}"
  - options = { target: 'external', subject: subject, body: body, title: @bn.badge.try(:current_holder_names) }
  %button= mail_to @bn.badge.current_holder_emails, "Open e-mail to request validations from #{holders_count} current Badge Holders", options
%br
- if holders_count < 4
  - boostrapper_emails = User.bootstrapper.map(&:mailto).join(' ')
  %button= mail_to boostrapper_emails, "Open e-mail to request grant from #{User.bootstrapper.count} Badge Bootstrappers", title: User.bootstrappers
.clear-both
- if librarian_or_admin?
  .admin-only
    .row
      %strong.large-3.columns.text-right Level Voted
      .large-6.columns= @badge_nomination.level_voted
      .large-3.columns
    .row
      %strong.large-3.columns.text-right Level Bootstrapped
      .large-6.columns= @badge_nomination.level_bootstrapped
      .large-3.columns
    .row
      %strong.large-3.columns.text-right Grant Status
      - if @badge_nomination.status == 'accepted'
        .large-6.columns= "Accepted at level #{@badge_nomination.level_granted}"
      - else
        .large-6.columns Pending, i.e. voting takes over
      .large-3.columns
    %button= link_to 'Add Validation', new_nomination_vote_path(badge_nomination_id: @badge_nomination.id)
  %h4 Validations
  %span.admin-only= render @validations
- else
  %h4 Validations
  = "Already nominated/bootstrapped #{@badge_nomination.validators.count} times"
%hr

- if librarian_or_admin?
  %p
  .admin-only
    %button= link_to 'Edit Nomination', edit_badge_nomination_path(@badge_nomination)
    %button= link_to 'Destroy Nomination', @badge_nomination, method: :delete, data: { confirm: 'Are you sure you want to permanently delete this nomination?' }
- else
  %button= link_to 'All Nominations', badge_nominations_path(status: 'waiting')
  %button= link_to 'Add Your Validation', new_nomination_vote_path(badge_nomination_id: @badge_nomination.id)